Repository ecmwf/atlas, pull requests merged in 2023-05, with the labels that each got.

#130 Improve robustness of conservative spherical polygon interpolation for high resolution meshes
  src/atlas/interpolation/method/unstructured/ConservativeSphericalPolygonInterpolation.cc
  src/atlas/interpolation/method/unstructured/ConservativeSphericalPolygonInterpolation.h
  src/atlas/util/ConvexSphericalPolygon.cc
  src/atlas/util/ConvexSphericalPolygon.h
  src/sandbox/interpolation/atlas-conservative-interpolation.cc
  src/tests/interpolation/test_interpolation_conservative.cc
  src/tests/util/test_convexsphericalpolygon.cc
Labels: approved-for-ci

#120 upgrade the halo exchange procedure for the function space 'PointCloud'
  src/atlas/functionspace/PointCloud.cc
  src/atlas/functionspace/PointCloud.h
  src/tests/functionspace/CMakeLists.txt
  src/tests/functionspace/test_pointcloud.cc
  src/tests/functionspace/test_pointcloud_haloexchange_2PE.cc
  src/tests/functionspace/test_pointcloud_haloexchange_3PE.cc
Labels: contributor, approved-for-ci

#133 Optimise array::helpers::ForEach for small arrays.
  src/atlas/array/helpers/ArrayForEach.h
  src/tests/array/test_array_foreach.cc
Labels: contributor, approved-for-ci

#135 Add function to build mesh from imported connectivity data
  src/atlas/CMakeLists.txt
  src/atlas/mesh/MeshBuilder.cc
  src/atlas/mesh/MeshBuilder.h
  src/tests/mesh/CMakeLists.txt
  src/tests/mesh/helper_mesh_builder.h
  src/tests/mesh/test_mesh_builder.cc
  src/tests/mesh/test_mesh_builder_parallel.cc
Labels: contributor
